name: Update Lambda Function
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - name: Install npm dependencies
      run: |
        npm ci
    - name: zip files
      run: |
        zip -q -r ./bundle.zip ./ -x "*.git*" -x "*.md"
    - name: upload to lambda
      run: |
        aws lambda update-function-code --function-name ExtractAndParseCSV --zip-file fileb://bundle.zip
